### ISSUE TITLE
Remove 'helloworld.py' and 'array.py"

### ISSUE THREAD

**Issue by MrMebelMan** [MrParkerr/Practice-#2]
We're starting over, wipe it all.

**Comment by MrParkerr** [comment]
Done Sir !

**Comment by MrMebelMan** [comment]
Reopening the issue, the files are still present in the repository. One more fuck up and you're fired.

**Comment by MrMebelMan** [comment]
Well done, Elon
